-- Create test user for authentication testing
-- Password: 123456

INSERT INTO auth.users (
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    phone_confirmed_at,
    confirmation_sent_at,
    recovery_sent_at,
    email_change_sent_at,
    new_email,
    new_phone,
    invited_at,
    action_link,
    email_change,
    new_email_change_sent_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at,
    is_sso_user,
    deleted_at,
    is_anonymous
) VALUES (
    '550e8400-e29b-41d4-a716-446655440000',
    'authenticated',
    'authenticated',
    'test@test.no',
    '$2a$10$LvBOZqcbFxPyQIVe7YAzN.DKrTwjWLjvKhRjMdMPiTgJvqRUfgmV6', -- bcrypt hash of "123456"
    NOW(),
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '{}',
    '{"full_name": "Test User"}',
    false,
    NOW(),
    NOW(),
    NULL,
    NULL,
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL,
    false,
    NULL,
    false
) ON CONFLICT (id) DO NOTHING;

-- Also create identity record if needed
INSERT INTO auth.identities (
    id,
    user_id,
    identity_data,
    provider,
    last_sign_in_at,
    created_at,
    updated_at
) VALUES (
    '550e8400-e29b-41d4-a716-446655440001',
    '550e8400-e29b-41d4-a716-446655440000',
    '{"sub": "550e8400-e29b-41d4-a716-446655440000", "email": "test@test.no"}',
    'email',
    NOW(),
    NOW(),
    NOW()
) ON CONFLICT (id) DO NOTHING;